# Generated by Django 4.0.6 on 2023-04-16 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muruga', '0002_rename_user_credentials_user_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_credential',
            name='likes',
            field=models.ManyToManyField(related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
